# Generated by Django 2.1.4 on 2018-12-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='audience',
            field=models.ManyToManyField(to='polls.User'),
        ),
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='polls.User'),
            preserve_default=False,
        ),
    ]
