# Generated by Django 2.1.4 on 2018-12-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_istimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='isTimed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
