# Generated by Django 2.1.4 on 2018-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181224_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'Maybe'), (-1, 'No')]),
        ),
    ]
