# Generated by Django 2.1.4 on 2019-01-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190101_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedchoice',
            name='content',
        ),
        migrations.AddField(
            model_name='timedchoice',
            name='end_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timedchoice',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
