# Generated by Django 2.1.4 on 2019-01-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190101_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Choice')),
                ('weekday', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            bases=('polls.choice',),
        ),
    ]
