# Generated by Django 2.1.4 on 2019-01-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_recurringchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timedchoice',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='recurringchoice',
            name='weekday',
            field=models.IntegerField(choices=[(5, 'Saturday'), (6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')]),
        ),
    ]
