# Generated by Django 2.1.4 on 2019-01-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190102_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isRegistered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurringchoice',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
